import { Router } from 'express';
import healthRoutes from './health.routes';
import authRoutes from './auth.routes';
import categoryRoutes from './category.routes';
import productRoutes from './product.routes';
import cartRoutes from './cart.routes';
import wishlistRoutes from './wishlist.routes';
import orderRoutes from './order.routes';
import addressRoutes from './address.routes';
import adminRoutes from './admin.routes';
import adminBrandRoutes from './admin-brand.routes';
import adminOrderRoutes from './admin-order.routes';
import adminUserRoutes from './admin-user.routes';
import adminDashboardRoutes from './admin-dashboard.routes';
import adminCouponRoutes from './admin-coupon.routes';
import adminReviewRoutes from './admin-review.routes';
import adminArticleRoutes from './admin-article.routes';
import adminInventoryRoutes from './admin-inventory.routes';
import uploadRoutes from './upload.routes';
import reviewRoutes from './review.routes';
import couponRoutes from './coupon.routes';
import paymentRoutes from './payment.routes';

const router = Router();

router.use(healthRoutes);
router.use(authRoutes);
router.use(categoryRoutes);
router.use(productRoutes);
router.use(cartRoutes);
router.use(wishlistRoutes);
router.use(orderRoutes);
router.use(addressRoutes);
router.use(reviewRoutes);
router.use(couponRoutes);
router.use(paymentRoutes);
router.use('/admin', adminRoutes);
router.use('/admin', adminBrandRoutes);
router.use('/admin', adminOrderRoutes);
router.use('/admin', adminUserRoutes);
router.use('/admin', adminDashboardRoutes);
router.use('/admin', adminCouponRoutes);
router.use('/admin', adminReviewRoutes);
router.use('/admin', adminArticleRoutes);
router.use('/admin', adminInventoryRoutes);
router.use(uploadRoutes);

export default router;
